### ISSUE TITLE
Generate Build script in Engine

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-runtime#12]
Previously the yaml parser was responsible for generating the shell script and deciding how it was passed to the container. This should be moved to the runtime engine. To do so, we should add a `Commands` and `Shell` attribute:

```diff
	type Step struct {
		Entrypoint   []string          `json:"entrypoint,omitempty"`
		Command      []string          `json:"command,omitempty"`
+		Commands     []string          `json:"commands,omitempty"`
+		Shell        []string          `json:"shell,omitempty"`
...
	}
```

The `commands` and `shell` should be used by the engine to generate the build script and inject this into the container so that it can be executed as the main entrypoint. Some implementation notes:

1. If the `commands` section is specific, it should always override the entrypoint and args
2. If the shell is empty we should default to `/bin/sh` on linux and `powershell` on windows (do we need to specify platform somewhere to enable this)?
3. The engine driver should choose how it wants to upload the script to the container
3. The script generator already exists in `drone-yaml-v1` and should be moved into this repository in an `engine/scripts` package so that it can be shared by all engine implementations
4. The Docker engine uploads the file using `docker cp` and then executes. We should continue to use this approach for Docker, but should use an engine-specific approach for kubernetes. Perhaps it could be added as a mounted secret? or maybe passed as an environment variable that we execute with `/bin/bash -c ${SCRIPT}`? Whatever works best.

Once the runtime is patched, we need to update the `drone-yaml-v1` parser to populate the `commands` and `shell` attributes, and we can remove the script generator code from the yaml package as well.

cc @metalmatze

**Comment by metalmatze** [comment]
For Kubernetes see http://blog.phymata.com/2017/07/29/inject-an-executable-script-into-a-container-in-kubernetes/. Not sure if this a good or bad practice though...

Edit:
Found yet another article: http://blog.xebia.com/kubernetes-ci-builders/

https://kubernetes.io/docs/tasks/inject-data-application/define-command-argument-container/

**Comment by tboerger** [comment]
No need for the init container within that example, I'm doing it like this for a different topic:

```
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: scripts
data:
  templates.sh: |-
    #!/usr/bin/env bash
    whoami

---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: example
spec:
  template:
    spec:
      containers:
      - name: example
        image: my/image
        volumeMounts:
        - name: scripts
          mountPath: /etc/scripts
      volumes:
      - name: scripts
        configMap:
          name: scripts
          defaultMode: 0755
          items:
          - key: templates.sh
            path: templates.sh
```
