### ISSUE TITLE
driver: qemu

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-runtime#14]
support qemu as the runtime engine. The corresponding yaml would be slightly different than docker, and would look something like this:

```
---
version: 1
kind: pipeline
type: qemu

settings:
  image: debian.img

platform:
  os: linux
  arch: amd64

steps:
- name: build
  commands:
  - go build
  - go test
```
