### ISSUE TITLE
driver: vmware fusion

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-runtime#15]
support vmware fusion. The yaml configuration would look something like below. The `type` parameter would be used to differentiate between vm and container pipelines, and would unmsarshal to a different structure.

```
---
version: 1
kind: pipeline
type: vmwarefusion

settings:
  image: osx.img

platform:
  os: osx
  arch: amd64

steps:
- name: build
  commands:
  - go build
  - go test
```
