### ISSUE TITLE
kubernetes: pipeline blocking

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-runtime#16]
the following yaml blocks in kubernetes:

```
kind: pipeline

steps:
- name: ping
  image: redis:4-alpine
  commands:
  - sleep 5
  - echo $REDIS_SERVICE_HOST
  - redis-cli -h $REDIS_SERVICE_HOST ping
- name: greetings
  image: golang:1.11
  commands:
  - echo hello
  - echo world

services:
- name: redis
  image: redis:4-alpine
  ports:
  - 6379
```

I suspect it is has something to do with either the `Wait` or `Tail` functions because I can see the containers are stopped in kubernetes. I will research further and post back results of my research.
