### ISSUE TITLE
feature: implement depends_on

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-runtime#22]
the depends_on keyword should enable execution of pipelines as a DAG. The runtime currently ignores depends_on, and executes pipeline steps sequentially.

**Comment by bradrydzewski** [comment]
Version 0.8 had a `group` field that allows you to group parallel tasks.   The goal with 1.0 was to replace this with a `depends_on` field that allows you to create a graph execution, which is going to be slightly more powerful.

```yaml
kind: pipeline
name: foo

steps:
- name: foo
  image: golang
  commands:
  - go build
  - go test

- name: bar
  image: node
  commands:
  - npm install
  - npm test

- name: baz
  image: plugins/slack
  settings:
    webhook:
      from_secret: webhook
  depends_on:
  - foo
  - bar
```

If none of the steps in the pipeline define the `depends_on` field, the runtime should execute each step sequentially. I created an [`isSerial`](https://github.com/drone/drone-runtime/blob/master/runtime/graph.go#L12) helper function for this, however, it is not currently being used.

The yaml already supports `depends_on` and passes this information to the runtime, so luckily we only need to update the runtime to support this feature. The next step would be to update the runner to properly determine and execute the next set of tasks. I started writing some code [here](https://github.com/drone/drone-runtime/blob/master/runtime/graph.go#L26) however it is not particularly efficient.

The above logic needs to be implemented [here](https://github.com/drone/drone-runtime/blob/master/runtime/runtime.go#L61:L74).

As a side note, we need to ensure that we handle cyclical references to prevent an infinite loop.
