### ISSUE TITLE
kubernetes: disable in-cluster authentication for spawned images

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-runtime#24]
Images spawned by kubernetes can access the kubernetes API using "in cluster" authentication. This should be disabled for containers that are spawned by the pipeline, or at least customizable in some way. Until this is resolved, the Kubernetes engine should be internal-use-only (do not use for public repositories that accept pull requests). I was hoping to have a solution in place already, but could use some help if anyone is interested.

**Comment by bradrydzewski** [comment]
edit, looks like we can do this:

```
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  automountServiceAccountToken: false
```

this may be a pretty simple fix ...
