### ISSUE TITLE
Cannot be used in openshift

### ISSUE THREAD

**Issue by zetaab** [drone/drone-runtime#35]
I am trying to run drone with kubernetes runtime in openshift. However, it cannot work because:

```
  volumes:
  - hostPath:
      path: /tmp/drone/zai6xqb3jgbxoh3lxx5xmibp1pxrgvu9/zai6xqb3jgbxoh3lxx5xmibp1pxrgvu9
      type: DirectoryOrCreate
```

https://kubernetes.io/docs/concepts/storage/volumes/

```
DirectoryOrCreate | If nothing exists at the given path, an empty directory will be created there as needed with permission set to 0755, having the same group and ownership with Kubelet.
```

this means that kubernetes will create folder with 755 (root is the owner). However, openshift by default does not allow executing containers as root. 

That is why we should have possibility to configure privileged parameter to true in all pods.

```
    securityContext:
      privileged: false
```

I think privileged can be configured in case of normal `step` things. However, we need to possibility to configure it in other steps as well like clone etc
