### ISSUE TITLE
set in config.json failed: no such file or directory

### ISSUE THREAD

**Issue by zetaab** [drone/drone-runtime#36]
I am running following pipeline using drone 1.0 rc3

```
kind: pipeline
name: default

steps:
- name: build
  image: golang
  commands:
  - go build
  - go test

  testing:
    image: golang:1.11
    group: build
    commands:
      - go get -u github.com/golang/lint/golint
      - make test

  build:
    image: golang:1.11
    group: build
    commands:
      - go get -u github.com/golang/dep/cmd/dep
      - dep ensure
      - make build_linux_amd64
```

when the new namespace is created and clone pod starts the result is following:

```
NAME                               READY     STATUS               RESTARTS   AGE
b4bfulps892q3o9kgqutcoqoqhvsnwgc   0/1       ContainerCannotRun   0          1m
```

```
Events:
  Type     Reason                 Age   From                        Message
  ----     ------                 ----  ----                        -------
  Normal   Scheduled              1m    default-scheduler           Successfully assigned b4bfulps892q3o9kgqutcoqoqhvsnwgc to dc2-dev-node-3-13
  Normal   SuccessfulMountVolume  1m    kubelet, dc2-dev-node-3-13  MountVolume.SetUp succeeded for volume "4ourscyc3ir93chjkjzqtn4pet72be97"
  Normal   SuccessfulMountVolume  1m    kubelet, dc2-dev-node-3-13  MountVolume.SetUp succeeded for volume "vjv54k4zj1b7vzbnhf7gy8i56lawmgd3"
  Normal   Pulling                1m    kubelet, dc2-dev-node-3-13  pulling image "docker.io/drone/git:latest"
  Normal   Pulled                 1m    kubelet, dc2-dev-node-3-13  Successfully pulled image "docker.io/drone/git:latest"
  Normal   Created                1m    kubelet, dc2-dev-node-3-13  Created container
  Warning  Failed                 1m    kubelet, dc2-dev-node-3-13  Error: failed to start container "b4bfulps892q3o9kgqutcoqoqhvsnwgc": Error response from daemon: oci runtime error: container_linux.go:247: starting container process caused "chdir to cwd (\"/drone/src\") set in config.json failed: no such file or directory"
```
