### ISSUE TITLE
kubernetes: Feature Request: taints + tolerations

### ISSUE THREAD

**Issue by paulreimer** [drone/drone-runtime#37]
It would help my use case of using kubernetes + Drone, and desiring to have k8s nodes dedicated to running Drone jobs.

This could work by having a cluster admin create k8s nodes with `taints`:
`kubectl taint nodes node1 dedicated=drone:NoSchedule`

And so a feature request for supporting config option in Drone to set matching `tolerations`:
```
spec:
  tolerations:
    - key: dedicated
      value: drone
```
