### ISSUE TITLE
Kubernetes: pipeline jobs created should include labels

### ISSUE THREAD

**Issue by max-rocket-internet** [drone/drone-runtime#45]
Currently the jobs that are created to run pipelines are missing the standard labels. I think we should at least add the label `k8s-app=drone` for jobs. This is standard for almost every resource on k8s and is currently missing. This would allow a user to run `kubectl delete job -l k8s-app=drone` for example.

I think we should also consider adding more labels. e.g. for build ID, repo, etc. I see we have annotations for these but not labels. Are the annotations used/read by either Drone itself or drone/controller? If not, then I would move all the annotations to labels. If they are used, then duplicate some of this data to the labels so they can be used with `kubectl <verb> -l xxx=yyy` 🙂

**Comment by bradrydzewski** [comment]
> Are the annotations used/read by either Drone itself or drone/controller

the only place we are really using labels is for configuring services:

```
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    io.drone.step.name: mysql
---
kind: Pod
metadata:
  labels:
    io.drone.step.name: mysql
```
