### ISSUE TITLE
driver: exec

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-runtime#46]
The `exec` driver will allow Pipeline executions on the host machine. This can be useful for workloads that cannot run inside containers, and for supporting additional operating systems, such as osx. Only trusted repositories would be allowed to use this pipeline type. The yaml itself would look something like this:

```
kind: pipeline
type: exec

platform:
  os: darwin
  arch: amd64

steps:
- name: build
  commands:
  - go build
  - go test
```

Example of all available fields for this driver type:

```
kind: pipeline
type: exec

platform:
  os: darwin
  arch: amd64

clone:
  depth: 50
  disable: false
  skip_verify: false

steps:
- name: build
  shell: /bin/sh
  environment:
    GOOS: darwin
    GOARCH: amd64
    PASSWORD:
      from_secret: password
  commands:
  - go test -v
  - go build -o hello-world
```

Useful for pipelines that consist only of Docker commands:

```
kind: pipeline
type: exec

steps:
- name: build
  commands:
  - docker build -t foo .
  - docker run -n bar foo
- name: cleanup
  commands:
  - docker rm bar
  - docker rmi foo
```
