### ISSUE TITLE
driver: aws

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-runtime#49]
create an aws driver that spins up servers on-deman

```
kind: pipeline
type: aws

config:
  image: ami-1a2b3c4d
  instance: t3.small
  region: us-west-2

credentials:
  from_secret: aws_credentials

steps:
- name: build
  commands:
  - docker build -t foo/bar .
  - docker push foo/bar
```
