### ISSUE TITLE
kubernetes: support named ports

### ISSUE THREAD

**Issue by bradrydzewski** [drone/drone-runtime#60]
when a service has > 1 port, the ports need names. Drone names the ports the same as the port number, but Kubernetes does not seem to like this.

```
ports:
- name: 80
  port: 80
- name: 443
  port: 443
```

the kubernetes documentation doesn't mention any naming restrictions, and yet here we are. So it appears we either need to a) require people name ports or b) find a port auto-naming scheme that kubernetes will accept.

**Comment by dvdmuckle** [comment]
According to https://github.com/drone/drone-runtime/blob/3e821e2abea3c652667da4531b070bdf08e953e8/engine/kube/util.go#L295, a port name is being created from the source port itself, however, in actual implementation, one receives an error like `default: Service "docker" is invalid: [spec.ports[0].name: Required value, spec.ports[1].name: Required value]`, which would indicate the names aren't being properly applied. This error message came when creating a service with two open ports, that looks like...
```
services:
  - name: docker
    image: docker:dind
    privileged: true
    ports:
    - 8080
    - 2375
```
